addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.13")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.6.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.9.20")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.10")
